server:
  port: 28090

spring:
  application:
    name: log-generator
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:28761}
  cloud:
    config:
      username: ${CONFIG_USERNAME:config}
      password: ${CONFIG_PASSWORD}

  r2dbc:
    url: ${DB_R2DBC_URL:r2dbc:pool:postgresql://localhost:5432/logdetect}
    username: ${DB_USERNAME:logdetect}
    password: ${DB_PASSWORD}
    properties:
      schema: generator
    pool:
      initial-size: 5
      max-size: 20

  datasource:
    url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/logdetect}
    username: ${DB_USERNAME:logdetect}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: generator
    default-schema: generator
    table: flyway_schema_history

logdetect:
  generator:
    target-url: ${GENERATOR_TARGET:http://localhost:8084/api/logs}
    events-per-second: ${GENERATOR_EPS:50}
    attack-ratio: ${GENERATOR_ATTACK_RATIO:0.05}
