create table outbox_messages
(
    id              bigint primary key generated by default as identity,
    aggregate_id    varchar(64)  not null,
    channel         varchar(16)  not null
        check (channel in ('ES', 'KAFKA', 'FILE', 'OTHERS')),
    destination     varchar(255) not null,
    payload         jsonb        not null,
    status          varchar(16)  not null default 'PENDING'
        check (status in ('PENDING', 'PUBLISHED', 'FAILED', 'DEAD')),
    attempts        int          not null default 0,
    next_attempt_at timestamptz  not null default now(),
    created_at      timestamptz  not null default now(),
    published_at    timestamptz,
    last_error      text
);

create index outbox_pending_idx on outbox_messages (status, next_attempt_at);
create index outbox_aggregate_idx on outbox_messages (aggregate_id);
