server:
  port: 28761

spring:
  application:
    name: log-eureka-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  security:
    user:
      name: ${CONFIG_USERNAME:config}
      password: ${CONFIG_PASSWORD}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
